### ISSUE TITLE
Malicious Users Can Duplicate Protocol Earned Yield By Transferring wCVX Tokens To Another Account

### ISSUE THREAD

**Issue by iamsahu** [yieldprotocol/vault-v2#341]
## Report

- https://github.com/code-423n4/2022-01-yield-findings/issues/86
- https://github.com/code-423n4/2022-01-yield-findings/issues/85

## Proposed fix
Reinstate `_beforeTokenTransfer`, or override `_transfer` to use `checkpoint` except when transferring between wrapper and join

**Comment by alcueca** [comment]
Has this been fixed, @iamsahu ?

**Comment by iamsahu** [comment]
This was fixed by completely removing the Wrapper token.
