### ISSUE TITLE
Create a standalone contract to enable `give`

### ISSUE THREAD

**Issue by alcueca** [yieldprotocol/vault-v2#402]
I'm thinking on a standalone contract, that can execute `cauldron.give()` for vaults that `msg.sender` owns, except if `vault.ilkId` is in a blacklist stored in that same contract.

**Comment by alcueca** [comment]
@iamsahu, could you please provide a link to the Giver PR and close this issue?

**Comment by iamsahu** [comment]
Here is the PR that closed this issue: https://github.com/yieldprotocol/vault-v2/pull/403
