### ISSUE TITLE
Port FYToken tests to foundry

### ISSUE THREAD

**Issue by alcueca** [yieldprotocol/vault-v2#415]
[Here](https://github.com/yieldprotocol/vault-v2/tree/master/test)

![image](https://user-images.githubusercontent.com/38806121/169798346-55d3720f-3811-47d5-8455-41fbfe7f79ad.png)

The Join tests (#416 ) should be ported first

**Comment by Sabnock01** [comment]
https://github.com/yieldprotocol/vault-v2/pull/463

**Comment by Sabnock01** [comment]
https://github.com/yieldprotocol/vault-v2/pull/463
