### ISSUE TITLE
On WitchV2, implement a filter for ilk/art and vault owners

### ISSUE THREAD

**Issue by alcueca** [yieldprotocol/vault-v2#442]
It is likely that in the near future we might want to run more than one liquidations engine simultaneously, either for A/B testing, or to have different liquidation strategies for different ink/art pairs.

I would add a mapping of addresses that the Witch won't auction vaults from, set via governance. That means that vaults owned by other liquidations engines won't be auctioned.

Likewise, and nested mapping of ink/art pairs that cannot be auctioned would allow us to avoid pain with pairs that shouldn't be liquidated, like DAI/DAI, fDAI/DAI, yvDAI/DAI, etc.

**Comment by bbonanno** [comment]
#443
