### ISSUE TITLE
Unprofessional and misleading naming

### ISSUE THREAD

**Issue by edgework** [yieldprotocol/vault-v2#541]
You're probably going to just ignore this and probably laugh but your naming conventions are stupid.  I lost so much time trying to understand what ink, art, pour, stir etc. etc. means.  Why do you name things this way?  Whats wrong with "collateral" or "debt" etc? I guess you really don't care about third parties integrating your stuff.   I showed my time wasted to my client and why and they've decided to drop YP support so I don't waste any more of my time and their money.

Your engineers need to grow up

**Comment by alcueca** [comment]
Hey @edgework, thanks for dropping by. Why didn't you ask for help on our discord or somewhere?

**Comment by alcueca** [comment]
Understood, feedback received. Have a nice day.

**Comment by abemilk** [comment]
@inversebrah get me in lil shid
